@startuml Desafio - Diagrama de Componentes
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' ----------------- TRANSACTION SERVICE IDEAL -----------------

Container(transactionService, "Transaction Service", "ASP.NET Core")

Component(tsApi, "TransactionsController", "API Layer")
Component(tsAuth, "OIDC Middleware", "Autenticação")
Component(tsApp, "Application Layer", "Commands/Handlers")
Component(tsDomain, "Domain Layer", "Entities/ValueObjects/DomainEvents")
Component(tsInfraRepo, "Repositories", "Implementações EF Core")
Component(tsOutboxRepo, "OutboxRepository", "Persistência do Outbox")
Component(tsDispatcher, "OutboxDispatcherWorker", "Envio confiável de eventos")
Component(tsKafka, "KafkaPublisher", "Publicação em Kafka")
Component(tsVault, "VaultSecretsProvider", "Segredos seguros")

Rel(tsApi, tsAuth, "Autentica requisição")
Rel(tsApi, tsApp, "Invoca caso de uso")
Rel(tsApp, tsDomain, "Manipula entidades")
Rel(tsApp, tsInfraRepo, "Repo acesso")
Rel(tsApp, tsOutboxRepo, "Grava outbox")
Rel(tsDispatcher, tsOutboxRepo, "Lê outbox pendente")
Rel(tsDispatcher, tsKafka, "Envia evento")
Rel(tsDispatcher, tsVault, "Lê segredo (Ideal)")

' ----------------- CONSOLIDATION SERVICE IDEAL -----------------

Container(consolidationService, "Consolidation Service", "ASP.NET Core")

Component(csApi, "ConsolidationsController", "API Layer")
Component(csAuth, "OIDC Middleware", "Autenticação")
Component(csQuery, "QueryHandlers", "Queries")
Component(csRepos, "ReadModel Repository", "EF Core")
Component(csDbCtx, "ReadDbContext", "EF Core")
Component(csConsumer, "KafkaConsumer", "Consome eventos")
Component(csAggregator, "AggregationService", "Agrega saldos")
Component(csCache, "RedisCacheProvider", "Camada de cache")
Component(csVault, "VaultSecretsProvider", "Segredos")

Rel(csApi, csAuth, "Autentica")
Rel(csApi, csQuery, "Consulta saldo")
Rel(csQuery, csCache, "Checa cache", "ideal")
Rel(csQuery, csRepos, "Consulta BD")
Rel(csRepos, csDbCtx, "Usa")

Rel(csConsumer, csAggregator, "Recebe evento")
Rel(csAggregator, csRepos, "Atualiza read model")
Rel(csAggregator, csCache, "Atualiza cache")
Rel(csConsumer, csVault, "Lê segredo ideal")

@enduml
