@startuml Transaction Service - MVP - Diagrama de Componentes
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(transactionService, "Transaction Service", "ASP.NET Core")

Component(transCtrl, "TransactionsController", "API Controller")
Component(appService, "TransactionApplicationService", "Coordena casos de uso")
Component(repo, "TransactionRepository", "Persistência via EF Core")
Component(dbCtx, "TransactionDbContext", "EF Core DbContext")
Component(outboxRepo, "OutboxRepository", "Grava eventos outbox")
Component(outboxWorker, "OutboxDispatcherWorker", "Publica eventos")
Component(rmqPub, "RabbitMqPublisher", "Publicador de mensagens")

Rel(transCtrl, appService, "Invoca")
Rel(appService, repo, "Grava/le transações")
Rel(appService, outboxRepo, "Grava evento")
Rel(outboxWorker, outboxRepo, "Lê eventos pendentes")
Rel(outboxWorker, rmqPub, "Publica eventos")
Rel(repo, dbCtx, "Usa")
Rel(outboxRepo, dbCtx, "Usa")

@enduml
