@startuml Desafio - Diagrama de Container - MVP
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Comerciante")

System_Boundary(cfs, "Cash Flow System - MVP") {

    Container(transactionService, "Transaction Service", "ASP.NET Core", "Recebe lançamentos, persiste e publica eventos.")

    Container(consolidationService, "Consolidation Service", "ASP.NET Core", "Consome eventos e mantém o saldo consolidado diário.")

    ContainerDb(transactionDb, "TransactionDB", "PostgreSQL", "Armazena transações e outbox.")

    ContainerDb(readDb, "ReadDB", "PostgreSQL", "Armazena saldos consolidados por dia.")
}

System_Ext(broker, "RabbitMQ", "Fila de eventos TransactionCreated")

Rel(user, transactionService, "POST /transactions")
Rel(user, consolidationService, "GET /consolidations/daily")

Rel(transactionService, transactionDb, "CRUD transações/outbox")
Rel(transactionService, broker, "Publica eventos TransactionCreated")

Rel(broker, consolidationService, "Entrega eventos TransactionCreated")
Rel(consolidationService, readDb, "Atualiza saldo diário (write)")

@enduml
